export * from './activity-logs.service';
import { ActivityLogsApiService } from './activity-logs.service';
export * from './authentication.service';
import { AuthenticationApiService } from './authentication.service';
export * from './available-for-users.service';
import { AvailableForUsersApiService } from './available-for-users.service';
export * from './configs.service';
import { ConfigsApiService } from './configs.service';
export * from './emails.service';
import { EmailsApiService } from './emails.service';
export * from './faqs.service';
import { FaqsApiService } from './faqs.service';
export * from './favourites.service';
import { FavouritesApiService } from './favourites.service';
export * from './files.service';
import { FilesApiService } from './files.service';
export * from './goals.service';
import { GoalsApiService } from './goals.service';
export * from './mailer-emails.service';
import { MailerEmailsApiService } from './mailer-emails.service';
export * from './passwords.service';
import { PasswordsApiService } from './passwords.service';
export * from './payments.service';
import { PaymentsApiService } from './payments.service';
export * from './plans.service';
import { PlansApiService } from './plans.service';
export * from './public-api.service';
import { PublicAPIApiService } from './public-api.service';
export * from './purchase-orders.service';
import { PurchaseOrdersApiService } from './purchase-orders.service';
export * from './routine-sessions.service';
import { RoutineSessionsApiService } from './routine-sessions.service';
export * from './routines.service';
import { RoutinesApiService } from './routines.service';
export * from './sessions.service';
import { SessionsApiService } from './sessions.service';
export * from './tips.service';
import { TipsApiService } from './tips.service';
export * from './user-plans.service';
import { UserPlansApiService } from './user-plans.service';
export * from './users.service';
import { UsersApiService } from './users.service';
export const APIS = [ActivityLogsApiService, AuthenticationApiService, AvailableForUsersApiService, ConfigsApiService, EmailsApiService, FaqsApiService, FavouritesApiService, FilesApiService, GoalsApiService, MailerEmailsApiService, PasswordsApiService, PaymentsApiService, PlansApiService, PublicAPIApiService, PurchaseOrdersApiService, RoutineSessionsApiService, RoutinesApiService, SessionsApiService, TipsApiService, UserPlansApiService, UsersApiService];
