/**
 * Training plans marketplace - API
 * Aplicacion de venta de rutinas de ejercicios
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FaqStatusEnum } from './faq-status-enum';


export interface FaqDto { 
    id: string;
    createdAt?: string | null;
    updatedAt?: string | null;
    category: string;
    question: string;
    answer: string;
    status: FaqStatusEnum;
    position: number;
}
export namespace FaqDto {
}


