/**
 * NestJS Dynamic Forms - Basic example
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FormItemKindInputTypeStringEnum = 'CHOISE_STRING' | 'EMAIL' | 'RICH_TEXT' | 'TEXT' | 'TEXTAREA' | 'HIDDEN_STRING';

export const FormItemKindInputTypeStringEnum = {
    CHOISE_STRING: 'CHOISE_STRING' as FormItemKindInputTypeStringEnum,
    EMAIL: 'EMAIL' as FormItemKindInputTypeStringEnum,
    RICH_TEXT: 'RICH_TEXT' as FormItemKindInputTypeStringEnum,
    TEXT: 'TEXT' as FormItemKindInputTypeStringEnum,
    TEXTAREA: 'TEXTAREA' as FormItemKindInputTypeStringEnum,
    HIDDEN_STRING: 'HIDDEN_STRING' as FormItemKindInputTypeStringEnum
};

