/**
 * NestJS Dynamic Forms - Basic example
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FormItemKindInputEnum = 'CHOISE_STRING' | 'DATE' | 'EMAIL' | 'FILES' | 'HIDDEN_STRING' | 'HIDDEN_DATE' | 'HIDDEN_OBJECT_ID' | 'HIDDEN_UUID_V4' | 'NUMBER' | 'RICH_TEXT' | 'SLIDE_TOGGLE' | 'TEXT' | 'TEXTAREA';

export const FormItemKindInputEnum = {
    CHOISE_STRING: 'CHOISE_STRING' as FormItemKindInputEnum,
    DATE: 'DATE' as FormItemKindInputEnum,
    EMAIL: 'EMAIL' as FormItemKindInputEnum,
    FILES: 'FILES' as FormItemKindInputEnum,
    HIDDEN_STRING: 'HIDDEN_STRING' as FormItemKindInputEnum,
    HIDDEN_DATE: 'HIDDEN_DATE' as FormItemKindInputEnum,
    HIDDEN_OBJECT_ID: 'HIDDEN_OBJECT_ID' as FormItemKindInputEnum,
    HIDDEN_UUID_V4: 'HIDDEN_UUID_V4' as FormItemKindInputEnum,
    NUMBER: 'NUMBER' as FormItemKindInputEnum,
    RICH_TEXT: 'RICH_TEXT' as FormItemKindInputEnum,
    SLIDE_TOGGLE: 'SLIDE_TOGGLE' as FormItemKindInputEnum,
    TEXT: 'TEXT' as FormItemKindInputEnum,
    TEXTAREA: 'TEXTAREA' as FormItemKindInputEnum
};

