/**
 * NestJS Dynamic Forms - Basic example
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FormItemWithChildrenEnum = 'ARRAY' | 'GROUP' | 'OBJECT' | 'SECTION';

export const FormItemWithChildrenEnum = {
    ARRAY: 'ARRAY' as FormItemWithChildrenEnum,
    GROUP: 'GROUP' as FormItemWithChildrenEnum,
    OBJECT: 'OBJECT' as FormItemWithChildrenEnum,
    SECTION: 'SECTION' as FormItemWithChildrenEnum
};

