/**
 * NestJS Dynamic Forms - Basic example
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormItemKindTitleEnum } from './form-item-kind-title-enum';


export interface FormItemTitle { 
    key: string;
    kind: FormItemKindTitleEnum;
    title: string;
}
export namespace FormItemTitle {
}


