/**
 * NestJS Dynamic Forms - Basic example
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormItemKindInputTypeDateEnum } from './form-item-kind-input-type-date-enum';


export interface FormItemResponseDate { 
    kind: FormItemKindInputTypeDateEnum;
    key: string;
    value?: string | null;
}
export namespace FormItemResponseDate {
}


