/**
 * NestJS Dynamic Forms - Basic example
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormItemKindInputTypeUUIDv4Enum } from './form-item-kind-input-type-uuidv4-enum';


export interface FormItemResponseUUIDv4 { 
    kind: FormItemKindInputTypeUUIDv4Enum;
    key: string;
    value?: string | null;
}
export namespace FormItemResponseUUIDv4 {
}


