/**
 * NestJS Dynamic Forms - Basic example
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormItemKindSlideToggleEnum } from './form-item-kind-slide-toggle-enum';


export interface FormItemSlideToggle { 
    key: string;
    kind: FormItemKindSlideToggleEnum;
    initialValue?: boolean | null;
    label?: string | null;
    required: boolean;
    readonly: boolean;
    disabled: boolean;
    description?: string | null;
    hint?: string | null;
}
export namespace FormItemSlideToggle {
}


