/**
 * NestJS Dynamic Forms - Basic example
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WithChildrenInner } from './with-children-inner';
import { FormItemKindArrayEnum } from './form-item-kind-array-enum';


export interface FormItemArray { 
    key: string;
    kind: FormItemKindArrayEnum;
    title?: string | null;
    childTitle?: string | null;
    minSize?: number | null;
    maxSize?: number | null;
    children: Array<WithChildrenInner>;
}
export namespace FormItemArray {
}


