/**
 * NestJS Dynamic Forms - Basic example
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FormItemKindElementOrUnknownEnum = 'ARRAY' | 'GROUP' | 'HTML' | 'IMAGE' | 'OBJECT' | 'SECTION' | 'TITLE' | 'UNKNOWN';

export const FormItemKindElementOrUnknownEnum = {
    ARRAY: 'ARRAY' as FormItemKindElementOrUnknownEnum,
    GROUP: 'GROUP' as FormItemKindElementOrUnknownEnum,
    HTML: 'HTML' as FormItemKindElementOrUnknownEnum,
    IMAGE: 'IMAGE' as FormItemKindElementOrUnknownEnum,
    OBJECT: 'OBJECT' as FormItemKindElementOrUnknownEnum,
    SECTION: 'SECTION' as FormItemKindElementOrUnknownEnum,
    TITLE: 'TITLE' as FormItemKindElementOrUnknownEnum,
    UNKNOWN: 'UNKNOWN' as FormItemKindElementOrUnknownEnum
};

