/**
 * NestJS Dynamic Forms - Basic example
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormItemKindEmailEnum } from './form-item-kind-email-enum';


export interface FormItemEmail { 
    key: string;
    kind: FormItemKindEmailEnum;
    initialValue?: string | null;
    label?: string | null;
    required: boolean;
    readonly: boolean;
    disabled: boolean;
    description?: string | null;
    hint?: string | null;
    length?: number | null;
    maxLength?: number | null;
    minLength?: number | null;
}
export namespace FormItemEmail {
}


