/**
 * NestJS Dynamic Forms - Basic example
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FormItemKindElementEnum = 'ARRAY' | 'GROUP' | 'HTML' | 'IMAGE' | 'OBJECT' | 'SECTION' | 'TITLE';

export const FormItemKindElementEnum = {
    ARRAY: 'ARRAY' as FormItemKindElementEnum,
    GROUP: 'GROUP' as FormItemKindElementEnum,
    HTML: 'HTML' as FormItemKindElementEnum,
    IMAGE: 'IMAGE' as FormItemKindElementEnum,
    OBJECT: 'OBJECT' as FormItemKindElementEnum,
    SECTION: 'SECTION' as FormItemKindElementEnum,
    TITLE: 'TITLE' as FormItemKindElementEnum
};

