/**
 * Training plans marketplace - API
 * Aplicacion de venta de rutinas de ejercicios
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserAndEmailDto } from './user-and-email-dto';


export interface PaginatedResponseOfUserAndEmailDto { 
    total: number;
    filtered?: number | null;
    showing: number;
    limit: number;
    offset: number;
    data: Array<UserAndEmailDto>;
}

