/**
 * Training plans marketplace - API
 * Aplicacion de venta de rutinas de ejercicios
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tag } from './tag';


export interface PlanInListDto { 
    id: string;
    createdAt?: string | null;
    updatedAt?: string | null;
    name: string;
    description: string;
    image?: string | null;
    price: number;
    discount: number;
    stars: number;
    tags: Array<Tag>;
    forGift: boolean;
    forSale: boolean;
    total: number;
    routines: number;
}

