/**
 * Training plans marketplace - API
 * Aplicacion de venta de rutinas de ejercicios
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlanForUserDto } from './plan-for-user-dto';
import { StatusEnum } from './status-enum';
import { RoutineNtsDto } from './routine-nts-dto';
import { GoalForUserDto } from './goal-for-user-dto';
import { PurchaseOrderForUserDtoRecipient } from './purchase-order-for-user-dto-recipient';


export interface PurchaseOrderForUserDto { 
    id: string;
    createdAt?: string | null;
    updatedAt?: string | null;
    /**
     * Reference to id field of users documents
     */
    user: string;
    price: number;
    discount: number;
    status: StatusEnum;
    userComments?: string | null;
    invoice?: string | null;
    recipient?: PurchaseOrderForUserDtoRecipient | null;
    forGift: boolean;
    total: number;
    goal: GoalForUserDto;
    plan: PlanForUserDto;
    routine: RoutineNtsDto;
}
export namespace PurchaseOrderForUserDto {
}


