/**
 * Training plans marketplace - API
 * Aplicacion de venta de rutinas de ejercicios
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoutineDto } from './routine-dto';
import { SessionDto } from './session-dto';


export interface RoutineSessionFilledDto { 
    id: string;
    createdAt?: string | null;
    updatedAt?: string | null;
    position: number;
    session: SessionDto;
    routine: RoutineDto;
}

