/**
 * Training plans marketplace - API
 * Aplicacion de venta de rutinas de ejercicios
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StatusEnum = 'ERROR' | 'FAILURE' | 'EXPIRED' | 'CANCELED' | 'CANCELED_BY_ADMIN' | 'CANCELED_BY_USER' | 'PENDING' | 'COMPLETED' | 'REFUND';

export const StatusEnum = {
    ERROR: 'ERROR' as StatusEnum,
    FAILURE: 'FAILURE' as StatusEnum,
    EXPIRED: 'EXPIRED' as StatusEnum,
    CANCELED: 'CANCELED' as StatusEnum,
    CANCELED_BY_ADMIN: 'CANCELED_BY_ADMIN' as StatusEnum,
    CANCELED_BY_USER: 'CANCELED_BY_USER' as StatusEnum,
    PENDING: 'PENDING' as StatusEnum,
    COMPLETED: 'COMPLETED' as StatusEnum,
    REFUND: 'REFUND' as StatusEnum
};

