/**
 * Training plans marketplace - API
 * Aplicacion de venta de rutinas de ejercicios
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSexEnum } from './user-sex-enum';


export interface UserProfileInputDto { 
    email?: string;
    fullname?: string;
    birthday?: string | null;
    sex?: UserSexEnum;
    tel?: string | null;
    whatsapp?: boolean | null;
    weight?: number | null;
    height?: number | null;
}
export namespace UserProfileInputDto {
}


