/**
 * Training plans marketplace - API
 * Aplicacion de venta de rutinas de ejercicios
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UserRoleEnum = 'USER' | 'ADMIN' | 'TEST';

export const UserRoleEnum = {
    USER: 'USER' as UserRoleEnum,
    ADMIN: 'ADMIN' as UserRoleEnum,
    TEST: 'TEST' as UserRoleEnum
};

